### PR TITLE
lsusb: Improve status display for SuperSpeedPlus hubs

### PR DESCRIPTION
**Pull request by robhancock**
Add more status information for SuperSpeedPlus hubs by using the
EXT_PORT_STATUS request to determine the actual link speed ID and number
of lanes that the hub reports it is connected with. This is needed to be
able to figure out the actual connection speed for SuperSpeedPlus
devices.

This requires parsing the BOS prior to the hub information, since we can
only use EXT_PORT_STATUS if the device actually has a SuperSpeedPlus
device capability.

Also fix some issues with the SuperSpeedPlus device capability parsing -
the speed attribute and speed ID counts were off by one, and the minimum
functional speed information is now parsed out.

Signed-off-by: Robert Hancock <hancockrwd@gmail.com>

### CODE REVIEW

**Comment by ValZapod** [comment]
What about USB4 stuff?

**Comment by robhancock** [comment]
> What about USB4 stuff?

Not sure, I don't have any such hardware to test against.

**Comment by ValZapod** [comment]
So apparently newest Orico LSDT USB4 supports both Thunderbolt 3 /4 and USB4.

Can you just look into how it is implemented in HW?

BTW, Thunderbolt 3 is not really 40 gbit/s bideriction, right, @gregkh? In reality it is video data (DisplayPort 1.2, 1.4 or even 2.0, 2.0 is 80 gbit/s uniderectional (some metadata, like EDID is still being send both ways, of course)) that has higher priority and can be up to 40 gbit/s biderictional. But data channel is only PCIe 3.0 x4, so only 32 gbit/s but even that is not correct, because Thunderbolt do not use the encoding of PCIe 3.0, 128b/130b! It still uses old PCIe 2.0 error checking, which is 8b/10b, so it is even worse. Again, I am sure about the video vs data part and its priority but not sure about 8b/10b.

**Comment by gregkh** [comment]
Looks good, thanks!

**Pull request merged**
