### PR TITLE
Patch bomb

### PR DESCRIPTION
**Pull request by grawity**
So when I was trying to figure out why lsusb.py from 010 wouldn't read usb.ids, I ended up doing... [a bit of hacking](https://github.com/grawity/code/commits/master/thirdparty/lsusb.py) on this script. Here I'm trying to rebase the useful parts on top of master (while still being py2-compatible).

This is all working, but I don't expect it to be in v011. I could split into several PRs if desired.

Main changes:

 * Output is now _sorted._ Yes, usb2 finally goes right in-between usb1 and usb3.
 * Colour mode is on by default for terminals (RFC?).
 * --long-options-are-supported
 * Removed hand-rolled binary search and replaced with Python dict lookup. As a consequence, the -w option (warn if unsorted) no longer exists.
 * Various cosmetic changes to make it look less like C code and more like Python code.

### CODE REVIEW

**Comment by gregkh** [comment]
Can you send this through email?  That would make it easier to review/apply some of these and iterate simpler.

thanks for doing this!

**Comment by grawity** [comment]
> Can you send this through email? That would make it easier to review/apply some of these and iterate simpler.

I'll do that then, is there a mailing list address or should I send it directly to you?

**Comment by gregkh** [comment]
linux-usb@vger.kernel.org would be good to cc: them do, and also to me so I don't miss them.

thanks!

**Comment by gregkh** [comment]
All but one now merged, so will close this pull request out.

Thanks for the patches!

**Pull request closed without merging**
