### PR TITLE
USB Audio Processing Unit: Type-specific descriptors

### PR DESCRIPTION
**Pull request by tlsa-ct**
This adds support for the extended descriptors specific to different processing unit types.

### CODE REVIEW

**Comment by gregkh** [comment]
Can you sign-off on these patches, like you did with previous ones?

**Comment by tlsa-ct** [comment]
Done!

**Comment by gregkh** [comment]
Looks great, thanks!

**Comment by tlsa-ct** [comment]
Great, thanks Greg!

**Pull request merged**
