### PR TITLE
Fix typos in lsusb.8.in

### PR DESCRIPTION
**Pull request by mb720**
Hi and thanks for lsusb!

I'd like to offer a handful of small spelling corrections to the man page.

### CODE REVIEW

**Comment by ValZapod** [comment]
LGTM in my part!

**Review by gregkh — CHANGES_REQUESTED** [review]
Need a signed-off-by: line please.

**Comment by mb720** [comment]
I followed the instructions [here](https://github.com/gregkh/usbutils/pull/125/checks?check_run_id=2487851372). I checked out the pull request locally and signed off using `git commit --amend --no-edit --signoff`. When trying to push with `git push --force-with-lease origin patch-1` I get this error message:

    remote: Permission to gregkh/usbutils.git denied to mb720.
    fatal: unable to access 'https://github.com/gregkh/usbutils.git/': The requested URL returned error: 403

Is this something I can fix on my end?

**Comment by gregkh** [comment]
And I do not know about how to force push with github issues, sorry.

What about a simple `git push --force` ?

**Comment by mb720** [comment]
> What about a simple `git push --force`?

Indeed, that worked, thanks :-)

**Review by gregkh — APPROVED** [review]

**Comment by gregkh** [comment]
thanks!

**Pull request merged**
